// NOTE: Admin Users Type
export const adminUserType = {
	GET_SUCCESS: 'GET_USER_SUCCESS',
	GET_ERROR: 'GET_USER_ERROR',
	DELETE_SUCCESS: 'DELETE_USER_SUCCESS',
	DELETE_ERROR: 'DELETE_USER_ERROR',
	IN_PROGRESS: 'REQUEST_USER_IN_PROGRESS'
};
